/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package tsg.service.base;

import com.liferay.counter.service.CounterLocalService;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.model.PersistedModel;
import com.liferay.portal.service.BaseLocalServiceImpl;
import com.liferay.portal.service.PersistedModelLocalServiceRegistryUtil;
import com.liferay.portal.service.ResourceLocalService;
import com.liferay.portal.service.ResourceService;
import com.liferay.portal.service.UserLocalService;
import com.liferay.portal.service.UserService;
import com.liferay.portal.service.persistence.ResourcePersistence;
import com.liferay.portal.service.persistence.UserPersistence;

import tsg.model.FlatOwner;

import tsg.service.FlatLocalService;
import tsg.service.FlatOwnerLocalService;
import tsg.service.FlatTenantLocalService;

import tsg.service.persistence.FlatOwnerPersistence;
import tsg.service.persistence.FlatPersistence;
import tsg.service.persistence.FlatTenantPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * The base implementation of the flat owner local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link tsg.service.impl.FlatOwnerLocalServiceImpl}.
 * </p>
 *
 * @author Whitemonk
 * @see tsg.service.impl.FlatOwnerLocalServiceImpl
 * @see tsg.service.FlatOwnerLocalServiceUtil
 * @generated
 */
public abstract class FlatOwnerLocalServiceBaseImpl extends BaseLocalServiceImpl
	implements FlatOwnerLocalService, IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link tsg.service.FlatOwnerLocalServiceUtil} to access the flat owner local service.
	 */

	/**
	 * Adds the flat owner to the database. Also notifies the appropriate model listeners.
	 *
	 * @param flatOwner the flat owner
	 * @return the flat owner that was added
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	public FlatOwner addFlatOwner(FlatOwner flatOwner)
		throws SystemException {
		flatOwner.setNew(true);

		return flatOwnerPersistence.update(flatOwner, false);
	}

	/**
	 * Creates a new flat owner with the primary key. Does not add the flat owner to the database.
	 *
	 * @param id the primary key for the new flat owner
	 * @return the new flat owner
	 */
	public FlatOwner createFlatOwner(long id) {
		return flatOwnerPersistence.create(id);
	}

	/**
	 * Deletes the flat owner with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param id the primary key of the flat owner
	 * @return the flat owner that was removed
	 * @throws PortalException if a flat owner with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	public FlatOwner deleteFlatOwner(long id)
		throws PortalException, SystemException {
		return flatOwnerPersistence.remove(id);
	}

	/**
	 * Deletes the flat owner from the database. Also notifies the appropriate model listeners.
	 *
	 * @param flatOwner the flat owner
	 * @return the flat owner that was removed
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	public FlatOwner deleteFlatOwner(FlatOwner flatOwner)
		throws SystemException {
		return flatOwnerPersistence.remove(flatOwner);
	}

	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(FlatOwner.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery)
		throws SystemException {
		return flatOwnerPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end)
		throws SystemException {
		return flatOwnerPersistence.findWithDynamicQuery(dynamicQuery, start,
			end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator orderByComparator) throws SystemException {
		return flatOwnerPersistence.findWithDynamicQuery(dynamicQuery, start,
			end, orderByComparator);
	}

	/**
	 * Returns the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	public long dynamicQueryCount(DynamicQuery dynamicQuery)
		throws SystemException {
		return flatOwnerPersistence.countWithDynamicQuery(dynamicQuery);
	}

	public FlatOwner fetchFlatOwner(long id) throws SystemException {
		return flatOwnerPersistence.fetchByPrimaryKey(id);
	}

	/**
	 * Returns the flat owner with the primary key.
	 *
	 * @param id the primary key of the flat owner
	 * @return the flat owner
	 * @throws PortalException if a flat owner with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	public FlatOwner getFlatOwner(long id)
		throws PortalException, SystemException {
		return flatOwnerPersistence.findByPrimaryKey(id);
	}

	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException, SystemException {
		return flatOwnerPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the flat owners.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param start the lower bound of the range of flat owners
	 * @param end the upper bound of the range of flat owners (not inclusive)
	 * @return the range of flat owners
	 * @throws SystemException if a system exception occurred
	 */
	public List<FlatOwner> getFlatOwners(int start, int end)
		throws SystemException {
		return flatOwnerPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of flat owners.
	 *
	 * @return the number of flat owners
	 * @throws SystemException if a system exception occurred
	 */
	public int getFlatOwnersCount() throws SystemException {
		return flatOwnerPersistence.countAll();
	}

	/**
	 * Updates the flat owner in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param flatOwner the flat owner
	 * @return the flat owner that was updated
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	public FlatOwner updateFlatOwner(FlatOwner flatOwner)
		throws SystemException {
		return updateFlatOwner(flatOwner, true);
	}

	/**
	 * Updates the flat owner in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param flatOwner the flat owner
	 * @param merge whether to merge the flat owner with the current session. See {@link com.liferay.portal.service.persistence.BatchSession#update(com.liferay.portal.kernel.dao.orm.Session, com.liferay.portal.model.BaseModel, boolean)} for an explanation.
	 * @return the flat owner that was updated
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	public FlatOwner updateFlatOwner(FlatOwner flatOwner, boolean merge)
		throws SystemException {
		flatOwner.setNew(false);

		return flatOwnerPersistence.update(flatOwner, merge);
	}

	/**
	 * Returns the flat local service.
	 *
	 * @return the flat local service
	 */
	public FlatLocalService getFlatLocalService() {
		return flatLocalService;
	}

	/**
	 * Sets the flat local service.
	 *
	 * @param flatLocalService the flat local service
	 */
	public void setFlatLocalService(FlatLocalService flatLocalService) {
		this.flatLocalService = flatLocalService;
	}

	/**
	 * Returns the flat persistence.
	 *
	 * @return the flat persistence
	 */
	public FlatPersistence getFlatPersistence() {
		return flatPersistence;
	}

	/**
	 * Sets the flat persistence.
	 *
	 * @param flatPersistence the flat persistence
	 */
	public void setFlatPersistence(FlatPersistence flatPersistence) {
		this.flatPersistence = flatPersistence;
	}

	/**
	 * Returns the flat owner local service.
	 *
	 * @return the flat owner local service
	 */
	public FlatOwnerLocalService getFlatOwnerLocalService() {
		return flatOwnerLocalService;
	}

	/**
	 * Sets the flat owner local service.
	 *
	 * @param flatOwnerLocalService the flat owner local service
	 */
	public void setFlatOwnerLocalService(
		FlatOwnerLocalService flatOwnerLocalService) {
		this.flatOwnerLocalService = flatOwnerLocalService;
	}

	/**
	 * Returns the flat owner persistence.
	 *
	 * @return the flat owner persistence
	 */
	public FlatOwnerPersistence getFlatOwnerPersistence() {
		return flatOwnerPersistence;
	}

	/**
	 * Sets the flat owner persistence.
	 *
	 * @param flatOwnerPersistence the flat owner persistence
	 */
	public void setFlatOwnerPersistence(
		FlatOwnerPersistence flatOwnerPersistence) {
		this.flatOwnerPersistence = flatOwnerPersistence;
	}

	/**
	 * Returns the flat tenant local service.
	 *
	 * @return the flat tenant local service
	 */
	public FlatTenantLocalService getFlatTenantLocalService() {
		return flatTenantLocalService;
	}

	/**
	 * Sets the flat tenant local service.
	 *
	 * @param flatTenantLocalService the flat tenant local service
	 */
	public void setFlatTenantLocalService(
		FlatTenantLocalService flatTenantLocalService) {
		this.flatTenantLocalService = flatTenantLocalService;
	}

	/**
	 * Returns the flat tenant persistence.
	 *
	 * @return the flat tenant persistence
	 */
	public FlatTenantPersistence getFlatTenantPersistence() {
		return flatTenantPersistence;
	}

	/**
	 * Sets the flat tenant persistence.
	 *
	 * @param flatTenantPersistence the flat tenant persistence
	 */
	public void setFlatTenantPersistence(
		FlatTenantPersistence flatTenantPersistence) {
		this.flatTenantPersistence = flatTenantPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the resource remote service.
	 *
	 * @return the resource remote service
	 */
	public ResourceService getResourceService() {
		return resourceService;
	}

	/**
	 * Sets the resource remote service.
	 *
	 * @param resourceService the resource remote service
	 */
	public void setResourceService(ResourceService resourceService) {
		this.resourceService = resourceService;
	}

	/**
	 * Returns the resource persistence.
	 *
	 * @return the resource persistence
	 */
	public ResourcePersistence getResourcePersistence() {
		return resourcePersistence;
	}

	/**
	 * Sets the resource persistence.
	 *
	 * @param resourcePersistence the resource persistence
	 */
	public void setResourcePersistence(ResourcePersistence resourcePersistence) {
		this.resourcePersistence = resourcePersistence;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		Class<?> clazz = getClass();

		_classLoader = clazz.getClassLoader();

		PersistedModelLocalServiceRegistryUtil.register("tsg.model.FlatOwner",
			flatOwnerLocalService);
	}

	public void destroy() {
		PersistedModelLocalServiceRegistryUtil.unregister("tsg.model.FlatOwner");
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		Thread currentThread = Thread.currentThread();

		ClassLoader contextClassLoader = currentThread.getContextClassLoader();

		if (contextClassLoader != _classLoader) {
			currentThread.setContextClassLoader(_classLoader);
		}

		try {
			return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
		}
		finally {
			if (contextClassLoader != _classLoader) {
				currentThread.setContextClassLoader(contextClassLoader);
			}
		}
	}

	protected Class<?> getModelClass() {
		return FlatOwner.class;
	}

	protected String getModelClassName() {
		return FlatOwner.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = flatOwnerPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = FlatLocalService.class)
	protected FlatLocalService flatLocalService;
	@BeanReference(type = FlatPersistence.class)
	protected FlatPersistence flatPersistence;
	@BeanReference(type = FlatOwnerLocalService.class)
	protected FlatOwnerLocalService flatOwnerLocalService;
	@BeanReference(type = FlatOwnerPersistence.class)
	protected FlatOwnerPersistence flatOwnerPersistence;
	@BeanReference(type = FlatTenantLocalService.class)
	protected FlatTenantLocalService flatTenantLocalService;
	@BeanReference(type = FlatTenantPersistence.class)
	protected FlatTenantPersistence flatTenantPersistence;
	@BeanReference(type = CounterLocalService.class)
	protected CounterLocalService counterLocalService;
	@BeanReference(type = ResourceLocalService.class)
	protected ResourceLocalService resourceLocalService;
	@BeanReference(type = ResourceService.class)
	protected ResourceService resourceService;
	@BeanReference(type = ResourcePersistence.class)
	protected ResourcePersistence resourcePersistence;
	@BeanReference(type = UserLocalService.class)
	protected UserLocalService userLocalService;
	@BeanReference(type = UserService.class)
	protected UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private String _beanIdentifier;
	private ClassLoader _classLoader;
	private FlatOwnerLocalServiceClpInvoker _clpInvoker = new FlatOwnerLocalServiceClpInvoker();
}