/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package tsg.model;

import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the FlatOwner service. Represents a row in the &quot;tsg_FlatOwner&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link tsg.model.impl.FlatOwnerModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link tsg.model.impl.FlatOwnerImpl}.
 * </p>
 *
 * @author Whitemonk
 * @see FlatOwner
 * @see tsg.model.impl.FlatOwnerImpl
 * @see tsg.model.impl.FlatOwnerModelImpl
 * @generated
 */
public interface FlatOwnerModel extends BaseModel<FlatOwner> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a flat owner model instance should use the {@link FlatOwner} interface instead.
	 */

	/**
	 * Returns the primary key of this flat owner.
	 *
	 * @return the primary key of this flat owner
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this flat owner.
	 *
	 * @param primaryKey the primary key of this flat owner
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this flat owner.
	 *
	 * @return the ID of this flat owner
	 */
	public long getId();

	/**
	 * Sets the ID of this flat owner.
	 *
	 * @param id the ID of this flat owner
	 */
	public void setId(long id);

	/**
	 * Returns the owner ID of this flat owner.
	 *
	 * @return the owner ID of this flat owner
	 */
	public long getOwnerId();

	/**
	 * Sets the owner ID of this flat owner.
	 *
	 * @param ownerId the owner ID of this flat owner
	 */
	public void setOwnerId(long ownerId);

	/**
	 * Returns the tsg ID of this flat owner.
	 *
	 * @return the tsg ID of this flat owner
	 */
	public long getTsgId();

	/**
	 * Sets the tsg ID of this flat owner.
	 *
	 * @param tsgId the tsg ID of this flat owner
	 */
	public void setTsgId(long tsgId);

	/**
	 * Returns the company ID of this flat owner.
	 *
	 * @return the company ID of this flat owner
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this flat owner.
	 *
	 * @param companyId the company ID of this flat owner
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this flat owner.
	 *
	 * @return the user ID of this flat owner
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this flat owner.
	 *
	 * @param userId the user ID of this flat owner
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this flat owner.
	 *
	 * @return the user uuid of this flat owner
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this flat owner.
	 *
	 * @param userUuid the user uuid of this flat owner
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this flat owner.
	 *
	 * @return the create date of this flat owner
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this flat owner.
	 *
	 * @param createDate the create date of this flat owner
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this flat owner.
	 *
	 * @return the modified date of this flat owner
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this flat owner.
	 *
	 * @param modifiedDate the modified date of this flat owner
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the flat ID of this flat owner.
	 *
	 * @return the flat ID of this flat owner
	 */
	public long getFlatId();

	/**
	 * Sets the flat ID of this flat owner.
	 *
	 * @param flatId the flat ID of this flat owner
	 */
	public void setFlatId(long flatId);

	/**
	 * Returns the from date of this flat owner.
	 *
	 * @return the from date of this flat owner
	 */
	public Date getFromDate();

	/**
	 * Sets the from date of this flat owner.
	 *
	 * @param fromDate the from date of this flat owner
	 */
	public void setFromDate(Date fromDate);

	/**
	 * Returns the to date of this flat owner.
	 *
	 * @return the to date of this flat owner
	 */
	public Date getToDate();

	/**
	 * Sets the to date of this flat owner.
	 *
	 * @param toDate the to date of this flat owner
	 */
	public void setToDate(Date toDate);

	/**
	 * Returns the percent of this flat owner.
	 *
	 * @return the percent of this flat owner
	 */
	public int getPercent();

	/**
	 * Sets the percent of this flat owner.
	 *
	 * @param percent the percent of this flat owner
	 */
	public void setPercent(int percent);

	/**
	 * Returns the area of this flat owner.
	 *
	 * @return the area of this flat owner
	 */
	public int getArea();

	/**
	 * Sets the area of this flat owner.
	 *
	 * @param area the area of this flat owner
	 */
	public void setArea(int area);

	/**
	 * Returns the shared of this flat owner.
	 *
	 * @return the shared of this flat owner
	 */
	public boolean getShared();

	/**
	 * Returns <code>true</code> if this flat owner is shared.
	 *
	 * @return <code>true</code> if this flat owner is shared; <code>false</code> otherwise
	 */
	public boolean isShared();

	/**
	 * Sets whether this flat owner is shared.
	 *
	 * @param shared the shared of this flat owner
	 */
	public void setShared(boolean shared);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(FlatOwner flatOwner);

	public int hashCode();

	public CacheModel<FlatOwner> toCacheModel();

	public FlatOwner toEscapedModel();

	public FlatOwner toUnescapedModel();

	public String toString();

	public String toXmlString();
}