/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package tsg.model;

import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the FlatTenant service. Represents a row in the &quot;tsg_FlatTenant&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link tsg.model.impl.FlatTenantModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link tsg.model.impl.FlatTenantImpl}.
 * </p>
 *
 * @author Whitemonk
 * @see FlatTenant
 * @see tsg.model.impl.FlatTenantImpl
 * @see tsg.model.impl.FlatTenantModelImpl
 * @generated
 */
public interface FlatTenantModel extends BaseModel<FlatTenant> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a flat tenant model instance should use the {@link FlatTenant} interface instead.
	 */

	/**
	 * Returns the primary key of this flat tenant.
	 *
	 * @return the primary key of this flat tenant
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this flat tenant.
	 *
	 * @param primaryKey the primary key of this flat tenant
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this flat tenant.
	 *
	 * @return the ID of this flat tenant
	 */
	public long getId();

	/**
	 * Sets the ID of this flat tenant.
	 *
	 * @param id the ID of this flat tenant
	 */
	public void setId(long id);

	/**
	 * Returns the company ID of this flat tenant.
	 *
	 * @return the company ID of this flat tenant
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this flat tenant.
	 *
	 * @param companyId the company ID of this flat tenant
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this flat tenant.
	 *
	 * @return the user ID of this flat tenant
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this flat tenant.
	 *
	 * @param userId the user ID of this flat tenant
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this flat tenant.
	 *
	 * @return the user uuid of this flat tenant
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this flat tenant.
	 *
	 * @param userUuid the user uuid of this flat tenant
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this flat tenant.
	 *
	 * @return the create date of this flat tenant
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this flat tenant.
	 *
	 * @param createDate the create date of this flat tenant
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this flat tenant.
	 *
	 * @return the modified date of this flat tenant
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this flat tenant.
	 *
	 * @param modifiedDate the modified date of this flat tenant
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the tenant ID of this flat tenant.
	 *
	 * @return the tenant ID of this flat tenant
	 */
	public long getTenantId();

	/**
	 * Sets the tenant ID of this flat tenant.
	 *
	 * @param tenantId the tenant ID of this flat tenant
	 */
	public void setTenantId(long tenantId);

	/**
	 * Returns the flat ID of this flat tenant.
	 *
	 * @return the flat ID of this flat tenant
	 */
	public long getFlatId();

	/**
	 * Sets the flat ID of this flat tenant.
	 *
	 * @param flatId the flat ID of this flat tenant
	 */
	public void setFlatId(long flatId);

	/**
	 * Returns the tsg ID of this flat tenant.
	 *
	 * @return the tsg ID of this flat tenant
	 */
	public long getTsgId();

	/**
	 * Sets the tsg ID of this flat tenant.
	 *
	 * @param tsgId the tsg ID of this flat tenant
	 */
	public void setTsgId(long tsgId);

	/**
	 * Returns the from date of this flat tenant.
	 *
	 * @return the from date of this flat tenant
	 */
	public Date getFromDate();

	/**
	 * Sets the from date of this flat tenant.
	 *
	 * @param fromDate the from date of this flat tenant
	 */
	public void setFromDate(Date fromDate);

	/**
	 * Returns the to date of this flat tenant.
	 *
	 * @return the to date of this flat tenant
	 */
	public Date getToDate();

	/**
	 * Sets the to date of this flat tenant.
	 *
	 * @param toDate the to date of this flat tenant
	 */
	public void setToDate(Date toDate);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(FlatTenant flatTenant);

	public int hashCode();

	public CacheModel<FlatTenant> toCacheModel();

	public FlatTenant toEscapedModel();

	public FlatTenant toUnescapedModel();

	public String toString();

	public String toXmlString();
}