/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package tsg.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import tsg.model.FlatTenant;
import tsg.model.FlatTenantModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the FlatTenant service. Represents a row in the &quot;tsg_FlatTenant&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link tsg.model.FlatTenantModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FlatTenantImpl}.
 * </p>
 *
 * @author Whitemonk
 * @see FlatTenantImpl
 * @see tsg.model.FlatTenant
 * @see tsg.model.FlatTenantModel
 * @generated
 */
public class FlatTenantModelImpl extends BaseModelImpl<FlatTenant>
	implements FlatTenantModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a flat tenant model instance should use the {@link tsg.model.FlatTenant} interface instead.
	 */
	public static final String TABLE_NAME = "tsg_FlatTenant";
	public static final Object[][] TABLE_COLUMNS = {
			{ "id_", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "tenantId", Types.BIGINT },
			{ "flatId", Types.BIGINT },
			{ "tsgId", Types.BIGINT },
			{ "fromDate", Types.TIMESTAMP },
			{ "toDate", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table tsg_FlatTenant (id_ LONG not null primary key,companyId LONG,userId LONG,createDate DATE null,modifiedDate DATE null,tenantId LONG,flatId LONG,tsgId LONG,fromDate DATE null,toDate DATE null)";
	public static final String TABLE_SQL_DROP = "drop table tsg_FlatTenant";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.tsg.model.FlatTenant"), true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.tsg.model.FlatTenant"), true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.tsg.model.FlatTenant"),
			true);
	public static long FLATID_COLUMN_BITMASK = 1L;
	public static long TENANTID_COLUMN_BITMASK = 2L;
	public static long TSGID_COLUMN_BITMASK = 4L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.tsg.model.FlatTenant"));

	public FlatTenantModelImpl() {
	}

	public long getPrimaryKey() {
		return _id;
	}

	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_id);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return FlatTenant.class;
	}

	public String getModelClassName() {
		return FlatTenant.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("tenantId", getTenantId());
		attributes.put("flatId", getFlatId());
		attributes.put("tsgId", getTsgId());
		attributes.put("fromDate", getFromDate());
		attributes.put("toDate", getToDate());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long id = (Long)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Long tenantId = (Long)attributes.get("tenantId");

		if (tenantId != null) {
			setTenantId(tenantId);
		}

		Long flatId = (Long)attributes.get("flatId");

		if (flatId != null) {
			setFlatId(flatId);
		}

		Long tsgId = (Long)attributes.get("tsgId");

		if (tsgId != null) {
			setTsgId(tsgId);
		}

		Date fromDate = (Date)attributes.get("fromDate");

		if (fromDate != null) {
			setFromDate(fromDate);
		}

		Date toDate = (Date)attributes.get("toDate");

		if (toDate != null) {
			setToDate(toDate);
		}
	}

	public long getId() {
		return _id;
	}

	public void setId(long id) {
		_id = id;
	}

	public long getCompanyId() {
		return _companyId;
	}

	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	public long getUserId() {
		return _userId;
	}

	public void setUserId(long userId) {
		_userId = userId;
	}

	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	public Date getCreateDate() {
		return _createDate;
	}

	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	public long getTenantId() {
		return _tenantId;
	}

	public void setTenantId(long tenantId) {
		_columnBitmask |= TENANTID_COLUMN_BITMASK;

		if (!_setOriginalTenantId) {
			_setOriginalTenantId = true;

			_originalTenantId = _tenantId;
		}

		_tenantId = tenantId;
	}

	public long getOriginalTenantId() {
		return _originalTenantId;
	}

	public long getFlatId() {
		return _flatId;
	}

	public void setFlatId(long flatId) {
		_columnBitmask |= FLATID_COLUMN_BITMASK;

		if (!_setOriginalFlatId) {
			_setOriginalFlatId = true;

			_originalFlatId = _flatId;
		}

		_flatId = flatId;
	}

	public long getOriginalFlatId() {
		return _originalFlatId;
	}

	public long getTsgId() {
		return _tsgId;
	}

	public void setTsgId(long tsgId) {
		_columnBitmask |= TSGID_COLUMN_BITMASK;

		if (!_setOriginalTsgId) {
			_setOriginalTsgId = true;

			_originalTsgId = _tsgId;
		}

		_tsgId = tsgId;
	}

	public long getOriginalTsgId() {
		return _originalTsgId;
	}

	public Date getFromDate() {
		return _fromDate;
	}

	public void setFromDate(Date fromDate) {
		_fromDate = fromDate;
	}

	public Date getToDate() {
		return _toDate;
	}

	public void setToDate(Date toDate) {
		_toDate = toDate;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			FlatTenant.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public FlatTenant toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (FlatTenant)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	public FlatTenant toUnescapedModel() {
		return (FlatTenant)this;
	}

	@Override
	public Object clone() {
		FlatTenantImpl flatTenantImpl = new FlatTenantImpl();

		flatTenantImpl.setId(getId());
		flatTenantImpl.setCompanyId(getCompanyId());
		flatTenantImpl.setUserId(getUserId());
		flatTenantImpl.setCreateDate(getCreateDate());
		flatTenantImpl.setModifiedDate(getModifiedDate());
		flatTenantImpl.setTenantId(getTenantId());
		flatTenantImpl.setFlatId(getFlatId());
		flatTenantImpl.setTsgId(getTsgId());
		flatTenantImpl.setFromDate(getFromDate());
		flatTenantImpl.setToDate(getToDate());

		flatTenantImpl.resetOriginalValues();

		return flatTenantImpl;
	}

	public int compareTo(FlatTenant flatTenant) {
		long primaryKey = flatTenant.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof FlatTenant)) {
			return false;
		}

		FlatTenant flatTenant = (FlatTenant)obj;

		long primaryKey = flatTenant.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		FlatTenantModelImpl flatTenantModelImpl = this;

		flatTenantModelImpl._originalTenantId = flatTenantModelImpl._tenantId;

		flatTenantModelImpl._setOriginalTenantId = false;

		flatTenantModelImpl._originalFlatId = flatTenantModelImpl._flatId;

		flatTenantModelImpl._setOriginalFlatId = false;

		flatTenantModelImpl._originalTsgId = flatTenantModelImpl._tsgId;

		flatTenantModelImpl._setOriginalTsgId = false;

		flatTenantModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<FlatTenant> toCacheModel() {
		FlatTenantCacheModel flatTenantCacheModel = new FlatTenantCacheModel();

		flatTenantCacheModel.id = getId();

		flatTenantCacheModel.companyId = getCompanyId();

		flatTenantCacheModel.userId = getUserId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			flatTenantCacheModel.createDate = createDate.getTime();
		}
		else {
			flatTenantCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			flatTenantCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			flatTenantCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		flatTenantCacheModel.tenantId = getTenantId();

		flatTenantCacheModel.flatId = getFlatId();

		flatTenantCacheModel.tsgId = getTsgId();

		Date fromDate = getFromDate();

		if (fromDate != null) {
			flatTenantCacheModel.fromDate = fromDate.getTime();
		}
		else {
			flatTenantCacheModel.fromDate = Long.MIN_VALUE;
		}

		Date toDate = getToDate();

		if (toDate != null) {
			flatTenantCacheModel.toDate = toDate.getTime();
		}
		else {
			flatTenantCacheModel.toDate = Long.MIN_VALUE;
		}

		return flatTenantCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(21);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", tenantId=");
		sb.append(getTenantId());
		sb.append(", flatId=");
		sb.append(getFlatId());
		sb.append(", tsgId=");
		sb.append(getTsgId());
		sb.append(", fromDate=");
		sb.append(getFromDate());
		sb.append(", toDate=");
		sb.append(getToDate());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(34);

		sb.append("<model><model-name>");
		sb.append("tsg.model.FlatTenant");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tenantId</column-name><column-value><![CDATA[");
		sb.append(getTenantId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>flatId</column-name><column-value><![CDATA[");
		sb.append(getFlatId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tsgId</column-name><column-value><![CDATA[");
		sb.append(getTsgId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fromDate</column-name><column-value><![CDATA[");
		sb.append(getFromDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>toDate</column-name><column-value><![CDATA[");
		sb.append(getToDate());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = FlatTenant.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			FlatTenant.class
		};
	private long _id;
	private long _companyId;
	private long _userId;
	private String _userUuid;
	private Date _createDate;
	private Date _modifiedDate;
	private long _tenantId;
	private long _originalTenantId;
	private boolean _setOriginalTenantId;
	private long _flatId;
	private long _originalFlatId;
	private boolean _setOriginalFlatId;
	private long _tsgId;
	private long _originalTsgId;
	private boolean _setOriginalTsgId;
	private Date _fromDate;
	private Date _toDate;
	private long _columnBitmask;
	private FlatTenant _escapedModel;
}